config/routes.rb
Wiki::Application.routes.draw do
  resources :articles
  resources :users
  resources :logins, :only => [:new, :create, :destroy]
  resources :categories
  post '/articles/:id/rollback', to: 'articles#rollback', as: 'rollback_article'
  post '/users/:id/deactivate', to: 'users#deactivate', as: 'deactivate_user'
  post '/users/:id/activate', to: 'users#activate', as: 'activate_user'
  get '/users/confirm/:key', to: 'users#confirm'
  

  root :to => 'articles#index'
end

app/models/article.rb
class Article < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  
  attr_accessible :title, :updates_attributes, :category_ids, :locked
  
  has_and_belongs_to_many :categories
  has_many :updates
  accepts_nested_attributes_for :updates
  
  validates :title, :uniqueness => true
  validates :title, :presence => true
  validates :title, :format => { :with => /^[a-zA-Z0-9 ]+$/ }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :revoke

  def index
    if params[:search] != nil && params[:search].size > 0
      @title = "Results for '#{params[:search]}'"
      @articles = Article.where("title ILIKE ?", "%#{params[:search]}%").order('updated_at DESC')
    elsif params[:cat] != nil
      @title = "Category '#{params[:cat]}'"
      @articles = Category.find_by_name(params[:cat]).articles.order('updated_at DESC')
    else
      @title = "All Articles"
      @articles = Article.order('updated_at DESC')
    end
  end
  
  def create
    authorize
    # raise(params.to_s)
    @article = Article.new(params[:article])
    
    if @article.save
      redirect_to(article_path(@article.slug))
    else
      render :new
    end
  end
  
  def new
    authorize
    @article = Article.new()
    @update = @article.updates.build
  end
  
  def edit
    authorize
    @article = Article.find(params[:id])
    
    if @article.locked && !current_user.admin
      @content = @article.updates.last.content
      @error="Article is locked. You cannot edit at this time."
      render :show
    end
    
    @update = @article.updates.last.dup
  end
  
  def show
    @article = Article.find(params[:id])
    @content = @article.updates.last.content
    @users = []
    @article.updates.each do |u|
      @users << u.user.username
    end
    @users.uniq!
  end
  
  def update
    authorize
    @article = Article.find(params[:id])
    
    if @article.update_attributes(params[:article])
      redirect_to(article_path(@article.slug))
    else
      render :edit
    end
  end
  
  def rollback
    # raise(params.to_s)
    authorize
    admin
    update = Update.create({:article_id => params[:id], :user_id => current_user.id, :content => params[:update][:update]})
    redirect_to(article_path(params[:id]))
  end
  
  def destroy
    authorize
    admin
    Article.delete(params[:id])
    redirect_to(articles_path)
  end
end

app/helpers/article_helper.rb
module ArticleHelper
  def list_categories(article)
    array = []
    article.categories.each do |cat|
      array << cat.name
    end
    array.join(", ")
  end
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <% @article.errors.full_messages.each do |error_msg| %>
    <p class="error"><%= error_msg %></p>
  <% end %>
<% end %>

<%= form_for @article do |article| %>

    <%= article.label :title %>
    <%= article.text_field :title %>

  <% if current_user.admin %>
      <%= article.label :locked %>
      <%= article.check_box :locked %>
  <% end %>
  <p>
    <label>Categories:</label><br />
    <%= collection_select(:article, :category_ids, Category.order('name ASC'), :id, :name,{:include_blank => 'None'},
    {:multiple => true, :name=>'article[category_ids][]',:selected => 0}) %>
  </p>

  <%= article.fields_for :updates, @update do |update| %>
    <%= update.hidden_field :user_id, :value => "#{session[:user_id]}"  %>
      <%= update.label :content %>
      <small>Content can be written in Markdown syntax. <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">Click here for a style guide.</a></small>
      <%= update.text_area :content, :rows => "10"%>
  <% end %>
  <%= article.submit %>
<% end %>

app/views/articles/_rollback.html.erb
<h1>Rollback Article</h1>
<%= form_for @article, :url => rollback_article_path, :method => :post do |update| %>

    <%= collection_select(:update, :update, @article.updates, :content, :username) %>
    <%= update.submit :value => "Rollback" %>
    
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render :partial => "form" %>
<% if current_user.admin %>
  <%= render :partial => "rollback" %>
<% end %>

app/views/articles/index.html.erb
<h1><%= @title %></h1>
<% if params[:search] != nil && params[:search].size > 0 %>    
  <p>"<%=params[:search]%>" returns <%=@articles.length%> result<%=pluralize(@articles.length)%>.
<% end %>
<% @articles.each do |article| %>
  <p>
    <%= link_to(article.title, article_path(article.slug)) %>  - <%= list_categories(article) %>
  </p>
<% end %>

app/views/articles/new.html.erb
<h1>Create New Article</h1>

<%= render :partial => "form" %>

app/views/articles/show.html.erb
<% if @error %>
  <h2 class="error"><%= @error %></h2>
<% end %>

<h1><%= @article.title %></h1>
<div id="articles">
  <h5>Categories: 
    <% @article.categories.each do |cat| %>
      <%= cat.name %>
    <% end %>
  </h5>
<p><%= markdown(@content) %></p>

<h5>Contributing Users</h5>
<p><%= @users.join(", ") %></p>
<% if current_user %>
  <p>
    <% if !@article.locked || current_user.admin %>
      <%= link_to("Edit", edit_article_path(@article.id)) %>
    <% else %>
      Article is LOCKED
    <% end %>
    <% if current_user.admin %>
    | <%= link_to("Delete", article_path(@article.id), :method => :delete) %>
      <% end %>
    </p>
  <% end %>
</div>