config/routes.rb
Wiki::Application.routes.draw do
  resources :articles
  resources :users
  resources :logins, :only => [:new, :create, :destroy]
  resources :categories
  post '/articles/:id/rollback', to: 'articles#rollback', as: 'rollback_article'
  post '/users/:id/deactivate', to: 'users#deactivate', as: 'deactivate_user'
  post '/users/:id/activate', to: 'users#activate', as: 'activate_user'
  get '/users/confirm/:key', to: 'users#confirm'
  

  root :to => 'articles#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  
  extend FriendlyId
  friendly_id :username
  
  has_secure_password
  
  
  attr_accessible :email, :fname, :lname, :password, :password_confirmation, :username
    
  has_many :updates
  
  
  validates :email, :uniqueness => true, :format => { :with => /.+@.+\..+/i }
  validates :fname, :presence => true
  validates :lname, :presence => true
  validates :username, :uniqueness => true, :format => { :with => /^[a-zA-Z0-9_]+$/ }
  validates :confirm_key, :presence => true
  
  def name
    fname + " " + lname
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :revoke
  
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end
  
  def edit
    if current_user.username == params[:id] || current_user.admin
      @user = User.find(params[:id])
    else
      redirect_to(:root)
    end
  end

  def create
    @user = User.new(params[:user])
    @user.confirm_key = Digest::SHA1.hexdigest @user.email
    
    if @user.save
      UserMailer.confirm_email(@user).deliver
      # session[:user_id] = @user.id # "auto-login"
      flash[:notice] = "Please check your email to confirm your account."
      redirect_to(:root)
    else
      render "new"
    end
  end
  
  def update
    @user = User.find(params[:id])
    @user.update_attributes(params[:user])
    
    redirect_to(:root)
  end

  def destroy
    # @user = User.find(params[:id])
    # if current_user.id = @user.id
    #   session[:user_id] = nil
    # end
    # @user.delete
    flash[:alert] = "Accounts cannot be removed, only deactivated."
    redirect_to(:users)
  end
  
  def deactivate
    user = User.find(params[:id])
    user.update_attribute(:inactive, "true")
    
    if current_user.id == user.id
      session[:user_id] = nil
      flash[:notice] = "Your account has been deactivated. Sorry to see you go."
    else
      flash[:notice] = "#{user.username}'s account has been deactivated."
    end
    
    redirect_to(:root)
  end

  def activate
    user = User.find(params[:id])
    user.update_attribute(:inactive, "false")
    
    redirect_to(:root)
  end
  
  def confirm
    @key = params[:key]
    @user = User.find_by_confirm_key(@key)
    
    if !@user.confirmed
      @user.update_attribute(:confirmed, true)
      session[:user_id] = @user.id # auto-login
      flash[:notice] = "Account successfully confirmed."
      redirect_to(:root)
    elsif @user.confirmed
      flash[:alert] = "Account has already been confirmed. Please log in."
      redirect_to(:new_login)
    else
      flash[:alert] = "Invalid Confirmation."
      redirect_to(:root)
    end
  end

end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |error_msg| %>
      <p><%= error_msg %></p>
    <% end %>
  <% end %>

  <%= f.label :email %>
  <%= f.text_field :email %>


  <%= f.label :username %>
  <%= f.text_field :username %>


  <%= f.label :fname, "First Name" %>
  <%= f.text_field :fname %>

  <%= f.label :lname, "Last Name" %>
  <%= f.text_field :lname %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  
  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User Info</h1>

<%= render :partial => "form" %>
<br>
<% if current_user.username == params[:id] || current_user.admin %>
  <p>
  <% if @user.inactive %>
    <%= form_tag(activate_user_path, method: "post") do %>
      <%= submit_tag("Activate User") %>
    <% end %>
  <% else%>
    <%= form_tag(deactivate_user_path, method: "post") do %>
      <%= submit_tag("Deactivate User") %>
    <% end %>
  <% end %>
  </p>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <p>
    <%= link_to(user.name, user_path(user.username)) %> (<%= user.username %>)
  </p>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render :partial => "form" %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<% if current_user && (current_user.username == params[:id]  || current_user.admin) %>
  <p>
  <%= link_to("Edit User Info", edit_user_path(@user.username)) %>
  </p>
<% end %>