config/routes.rb
Wiki::Application.routes.draw do
  resources :articles
  resources :users
  resources :logins, :only => [:new, :create, :destroy]
  resources :categories
  post '/articles/:id/rollback', to: 'articles#rollback', as: 'rollback_article'
  post '/users/:id/deactivate', to: 'users#deactivate', as: 'deactivate_user'
  post '/users/:id/activate', to: 'users#activate', as: 'activate_user'
  get '/users/confirm/:key', to: 'users#confirm'
  

  root :to => 'articles#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  
  has_and_belongs_to_many :articles
  
  validates :name, :presence => true, :uniqueness => true
  
  def to_s
    name
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :revoke, :authorize, :admin
  
  def index
    @categories = Category.all
  end
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(params[:category])
    
    if @category.save
      redirect_to(:categories)
    else
      render "new"
    end
  end
  
  def show
    @category = Category.find(params[:id])
  end
  
  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    @category.update_attributes(params[:category])
    
    redirect_to(:categories)
  end
  
  def destroy
    @category = Category.find(params[:id])
    @category.delete
    
    redirect_to(:categories)
  end
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <% if @category.errors.any? %>
    <% @category.errors.full_messages.each do |error_msg| %>
      <p><%= error_msg %></p>
    <% end %>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  
  <%= f.submit %>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= render :partial => "form" %>

app/views/categories/index.html.erb
<h1>All Categories</h1>

<ul>
  <% @categories.each do |c| %>
    <li><%= link_to(c.name, category_path(c.id)) %></li>
  <% end %>
<ul>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render :partial => "form" %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<p>
  <%= link_to("Edit", edit_category_path(@category.id)) %> |
  <%= link_to("Delete", category_path(@category.id), :method => :delete) %>
</p>

<h3>Related Articles:</h3>

<ul>
  <% @category.articles.each do |a| %>
    <li><%= link_to(a.title, article_path(a.slug))%></li>
  <% end %>
</ul>