config/routes.rb
Wiki::Application.routes.draw do
  resources :articles
  resources :users
  resources :logins, :only => [:new, :create, :destroy]
  resources :categories
  post '/articles/:id/rollback', to: 'articles#rollback', as: 'rollback_article'
  post '/users/:id/deactivate', to: 'users#deactivate', as: 'deactivate_user'
  post '/users/:id/activate', to: 'users#activate', as: 'activate_user'
  get '/users/confirm/:key', to: 'users#confirm'
  

  root :to => 'articles#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wiki</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="container">

  <div id="header">
    <a href="/"><img src="/assets/layout/OCS_star_75x75.png" width="75px" height="75px" alt="Omaha Code School Star" />
    <h1>Omaha <span style="font-family: Signika-Semibold, sans-serif;">Code</span> School Wiki</h1></a>
  </div>
    
  <div id="content" class="clearfix">
      <div id="top_nav">
        <div id="user_status">
          <p>
            <% if current_user %>
              Hi, <%= link_to(current_user.fname, user_path(current_user.username)) %>! |
              <%= link_to("Create New Article", :new_article) %> |
              <%= link_to("Log Out", login_path(current_user.id), :method => :delete) %> |
            <% else %>
              <%= link_to("Sign Up", :new_user) %> | 
              <%= link_to("Log In", :new_login) %> |
              <%= link_to("Create New Article", :new_article) %> |
            <% end %>
            <%= link_to("Home", :root)%>
          </p>
        </div>
        <div id="search_nav">
          <form name="search" action="/articles" method="get">
            <%= text_field_tag 'search', nil, placeholder: 'Enter search term...' %>
            <input type="submit" value="GO!">
          </form>
        </div>
      </div>
      
      <div id="left_column">
        <% if current_user %>
          <div class="left_column_section">
            <h2>
              <% if current_user.admin%>
                Admin
              <% else %>
                User
              <% end %>
            </h2>
            <ul>
              <li><%= link_to("View Profile", user_path(current_user.username))%></li>
              <li><%= link_to("Edit Profile", edit_user_path(current_user.username)) %></li>
              <% if current_user.admin %>
                <li><%= link_to("View All Categories", :categories) %></li>
                <li><%= link_to("View All Users", :users) %></li>
              <% end %>
              <li><%= link_to("Log Out", login_path(current_user.id), :method => :delete) %></li>
            </ul>
          </div>
        <% end %>
        <div class="left_column_section">
          <h2>Categories</h2>
          <ul>
            <% Category.order('name').each do |c| %>
              <li><a href="/articles?cat=<%= c.name %>"><%= c.name %></a></li>
            <% end %>
          </ul>
        </div>
      </div>
      
      <div id="right_column">
        <% if flash[:notice] || flash[:alert] %>
          <div id="flash">
            <p id="notice"><%= flash[:notice] %></p>
            <p id="alert"><%= flash[:alert] %></p>
          </div>
        <% end %>
        <%= yield %>
      </div>
    </div>
  
  <div id="footer_above"></div>
  
  <div id="footer">
    <p>Created by Cara Heacock, Matt Hova, and Andy von Dohren as a project for Omaha Code School.<br />
The Omaha Code School Wiki is not officially affiliated with Omaha Code School other than the developers being students there.</p>
  </div>

</div>

</body>
</html>